version: 0.2

env:
  variables:
    PYTHON_ENV: "production"
    DOCKER_BUILDKIT: "1"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - |
        echo "=== API Build Stage ==="
        echo Installing backend dependencies...
        echo "Working directory:"
        pwd
        echo "Directory structure:"
        ls -la
        cd packages/api
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pylint flake8 bandit safety

  pre_build:
    commands:
      - |
        echo "=== Pre-Build Checks ==="
        cd packages/api
        echo Running code quality checks...
        python -m pylint src/app.py --exit-zero || echo "Pylint check completed with warnings"
        python -m flake8 src/ tests/ --max-line-length=120 --exit-zero || echo "Flake8 check completed"
        python -m bandit -r src/ -ll --exit-zero || echo "Bandit security check completed"
        python -m safety check --json || echo "Safety check completed"
        echo Running unit tests...
        pytest tests/ --cov=src --cov-report=xml --cov-report=html --cov-report=term -v || echo "Some tests may have failed, continuing build..."
        echo Logging in to Amazon ECR...
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
        COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        IMAGE_TAG=${COMMIT_HASH:=latest}
        echo "Image will be tagged as $IMAGE_TAG"

  build:
    commands:
      - |
        echo "=== Building Docker Image ==="
        cd packages/api
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Docker image built successfully"
        echo Pushing Docker image to ECR...
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Docker image pushed successfully"

artifacts:
  files:
    - packages/api/requirements.txt
    - packages/api/pyproject.toml
  name: api-build-artifacts
  secondary-artifacts:
    coverage:
      files:
        - packages/api/coverage.xml
        - packages/api/htmlcov/**/*
      name: api-coverage-report

reports:
  pytest-reports:
    files:
      - packages/api/coverage.xml
    file-format: 'COBERTURAXML'

cache:
  paths:
    - /root/.cache/pip/**/*

