version: 0.2

env:
  variables:
    NODE_ENV: "staging"
    DOCKER_BUILDKIT: "1"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - |
        echo "=== API Build Stage ==="
        echo Installing backend dependencies...
        echo "Working directory:"
        pwd
        echo "Directory structure:"
        ls -la
        cd packages/api
        npm install

  pre_build:
    commands:
      - |
        echo "=== Pre-Build Checks ==="
        cd packages/api
        echo Running code quality checks...
        npm run lint
        echo Running unit tests...
        npm test
        echo Logging in to Amazon ECR...
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
        COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        IMAGE_TAG=${COMMIT_HASH:=latest}
        echo "Image will be tagged as $IMAGE_TAG"

  build:
    commands:
      - |
        echo "=== Building Docker Image ==="
        cd packages/api
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Docker image built successfully"
        echo Pushing Docker image to ECR...
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Docker image pushed successfully"

artifacts:
  files:
    - packages/api/package-lock.json
    - packages/api/package.json
  name: api-build-artifacts
  secondary-artifacts:
    coverage:
      files:
        - packages/api/coverage.xml
        - packages/api/htmlcov/**/*
      name: api-coverage-report

reports:
  pytest-reports:
    files:
      - packages/api/coverage.xml
    file-format: 'COBERTURAXML'

cache:
  paths:
    - /root/.cache/pip/**/*

