version: 0.2

env:
  variables:
    NODE_ENV: "staging"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - |
        echo "=== API Test Stage ==="
        npm install --upgrade awscli requests

  build:
    commands:
      - |
        echo "=== Testing API Health Endpoint ==="
        echo "ALB DNS Name: $ALB_DNS_NAME"
        echo "Testing health endpoint..."
        
        MAX_RETRIES=10
        RETRY_COUNT=0
        HEALTH_CHECK_PASSED=false
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          echo "Attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES"
          
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 http://$ALB_DNS_NAME/health || echo "000")
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✓ Health check passed! HTTP Status: $HTTP_CODE"
            HEALTH_CHECK_PASSED=true
            break
          else
            echo "✗ Health check failed. HTTP Status: $HTTP_CODE"
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "Waiting 15 seconds before retry..."
              sleep 15
            fi
          fi
        done
        
        if [ "$HEALTH_CHECK_PASSED" = "false" ]; then
          echo "✗ Health check failed after $MAX_RETRIES attempts"
          echo "Service may still be starting. Checking ECS service status..."
          aws ecs describe-services --cluster $ECS_CLUSTER_NAME --services $ECS_SERVICE_NAME
          exit 1
        fi
        
        echo "=== Running Additional API Tests ==="
        echo "Testing API root endpoint..."
        curl -f http://$ALB_DNS_NAME/ || echo "Root endpoint test completed"
        
        echo "=== Test Stage Completed Successfully ==="

artifacts:
  files:
    - "**/*"
  name: api-test-artifacts

